// Sample data used as fallback when database is empty
// All real data comes from Supabase

export const SAMPLE_CATEGORIES = [
  { id: '1', name: 'Dresses', slug: 'dresses', image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80', parent_id: null },
  { id: '2', name: 'Tops', slug: 'tops', image: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&q=80', parent_id: null },
  { id: '3', name: 'Bottoms', slug: 'bottoms', image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&q=80', parent_id: null },
  { id: '4', name: 'Ethnic Wear', slug: 'ethnic-wear', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80', parent_id: null },
  { id: '5', name: 'Western Wear', slug: 'western-wear', image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80', parent_id: null },
  { id: '6', name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&q=80', parent_id: null },
];

export const SAMPLE_PRODUCTS = [
  {
    id: '1',
    name: 'Silk Wrap Dress',
    slug: 'silk-wrap-dress',
    description: 'An elegant silk wrap dress that drapes beautifully, perfect for evening occasions.',
    price: 189.00,
    discount: 15,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Burgundy', 'Black', 'Ivory'],
    stock: 24,
    category_id: '1',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80',
    ],
    is_featured: true,
    is_trending: true,
    rating: 4.7,
    review_count: 128,
  },
  {
    id: '2',
    name: 'Cashmere Blend Sweater',
    slug: 'cashmere-blend-sweater',
    description: 'Luxuriously soft cashmere blend sweater for effortless everyday style.',
    price: 145.00,
    discount: 0,
    sizes: ['S', 'M', 'L'],
    colors: ['Camel', 'Cream', 'Dusty Rose'],
    stock: 42,
    category_id: '2',
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80',
    ],
    is_featured: true,
    is_trending: false,
    rating: 4.5,
    review_count: 87,
  },
  {
    id: '3',
    name: 'High-Waist Linen Trousers',
    slug: 'high-waist-linen-trousers',
    description: 'Relaxed-fit high-waist linen trousers with a modern silhouette.',
    price: 98.00,
    discount: 10,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Sand', 'White', 'Olive'],
    stock: 36,
    category_id: '3',
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80',
    ],
    is_featured: false,
    is_trending: true,
    rating: 4.3,
    review_count: 54,
  },
  {
    id: '4',
    name: 'Embroidered Anarkali Suit',
    slug: 'embroidered-anarkali-suit',
    description: 'Intricately embroidered Anarkali suit with dupatta, perfect for festive occasions.',
    price: 275.00,
    discount: 20,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blush Pink', 'Royal Blue', 'Sage Green'],
    stock: 18,
    category_id: '4',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80',
    ],
    is_featured: true,
    is_trending: true,
    rating: 4.9,
    review_count: 203,
  },
  {
    id: '5',
    name: 'Tailored Blazer',
    slug: 'tailored-blazer',
    description: 'Sharply tailored blazer with a relaxed fit, ideal for workwear and beyond.',
    price: 165.00,
    discount: 0,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Tan', 'Grey'],
    stock: 30,
    category_id: '5',
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80',
    ],
    is_featured: false,
    is_trending: true,
    rating: 4.6,
    review_count: 95,
  },
  {
    id: '6',
    name: 'Pearl Drop Earrings',
    slug: 'pearl-drop-earrings',
    description: 'Delicate pearl drop earrings with gold-plated hardware.',
    price: 48.00,
    discount: 0,
    sizes: ['One Size'],
    colors: ['Gold', 'Silver'],
    stock: 65,
    category_id: '6',
    images: [
      'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=800&q=80',
    ],
    is_featured: true,
    is_trending: false,
    rating: 4.8,
    review_count: 156,
  },
  {
    id: '7',
    name: 'Floral Maxi Dress',
    slug: 'floral-maxi-dress',
    description: 'Flowing floral maxi dress with a cinched waist and sweetheart neckline.',
    price: 135.00,
    discount: 25,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Rose Garden', 'Blue Meadow'],
    stock: 19,
    category_id: '1',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80',
    ],
    is_featured: false,
    is_trending: true,
    rating: 4.4,
    review_count: 72,
  },
  {
    id: '8',
    name: 'Satin Camisole Top',
    slug: 'satin-camisole-top',
    description: 'Versatile satin camisole with delicate lace trim detailing.',
    price: 62.00,
    discount: 0,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Champagne', 'Black', 'Dusty Mauve'],
    stock: 48,
    category_id: '2',
    images: [
      'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80',
    ],
    is_featured: true,
    is_trending: false,
    rating: 4.2,
    review_count: 41,
  },
];

export const SAMPLE_BANNERS = [
  {
    id: '1',
    title: 'Spring Collection',
    subtitle: 'Discover the new season',
    image_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1600&q=80',
    link: '/products?category=dresses',
    position: 'hero',
    is_active: true,
  },
  {
    id: '2',
    title: 'Up to 30% Off',
    subtitle: 'On selected ethnic wear',
    image_url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1200&q=80',
    link: '/products?category=ethnic-wear',
    position: 'mid',
    is_active: true,
  },
];
